[package]
name = "hook-keys-desktop"
version = "1.0.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }
cc = "1"

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = [] }
cpal = "0.16"
midir = "0.10"
base64 = "0.22"

[profile.release]
lto = "thin"
codegen-units = 4
strip = true
